source env.rc

SCHEMA=PARQUET
#INPATH=sbtest/out1/export-0

INPATH=sbtest/l.csv

TABLE=PARQUETTA


loadintotable() {

    local -r NO=$1

    local -r TMP=`mktemp`
    local -r TABLEDEST=$SCHEMA.$TABLE
    local -r TABLESOU=$SCHEMA.$TABLE$NO

cat << EOF > $TMP
    CONNECT TO BLUDB USER $USER USING $PASSWORD;

    DROP TABLE $TABLESOU IF EXISTS;

    CREATE TABLE $TABLESOU LIKE $TABLEDEST;

    SELECT COUNT(*) FROM $TABLESOU;
    SELECT COUNT(*) FROM $TABLEDEST;

    CALL SYSPROC.ADMIN_CMD('LOAD FROM S3::$ENDPOINT::$AWSKEY::$AWSSECRETKEY::$BUCKET::$INPATH OF DEL INSERT INTO $TABLESOU');

    SELECT COUNT(*) FROM $TABLESOU;

    INSERT INTO $TABLEDEST (SELECT * FROM $TABLESOU);

    SELECT COUNT(*) FROM $TABLEDEST;


    TERMINATE;

EOF

cat $TMP

db2 -tvf $TMP

}

test() {

db2 CONNECT TO BLUDB USER $USER USING $PASSWORD

db2 "DROP TABLE $TABLENAME IF EXISTS"

db2 "CREATE TABLE $TABLENAME LIKE "

db2 "CALL SYSPROC.ADMIN_CMD('LOAD FROM S3::$ENDPOINT::$AWSKEY::$AWSSECRETKEY::$BUCKET::$INPATH OF DEL INSERT INTO $TABLENAME')"

db2 terminate
}

loadintotable $1